### ISSUE TITLE
Falling blocks do not break torches, carpets, plants etc.

### ISSUE THREAD

**Issue by Pilvinen** [ExtendedAlpha/ExtendedAlpha-Core#3]
1) Place a few torches downhill
2) Cause a landslide
3) The landslide will totally be consumed by the torches.

I want to have an option where you can configure which blocks get broken by the falling blocks, ie. torches, flowers, plants, carpets etc which would pop up as items if drop items option is enabled.

desh promised to add this 1-2 years ago but stopped development of Landslide.
Then ~6-8 months ago the guy who had the Spigot version of Landslide promised to add this. Didn't deliver either, disappeared.

Will you please add this? Thanks.

**Comment by ExileDev** [comment]
This would be super easy to add but i'll have to look into some methods so it won't kill your server with lag and cause a block like a torch might render wrong and kill the server.

**Comment by ExileDev** [comment]
At the moment this feature will not be added as it might end up kill everyone servers.
